"""Render task drafts into Terminal-Bench Science text files."""

from __future__ import annotations

import json

from .models import TaskDraft


def render_instruction(draft: TaskDraft) -> str:
    sections = [f"# {draft.brief.title}"]
    if draft.brief.research_context.strip():
        sections.extend(("## Scientific context", draft.brief.research_context.strip()))
    sections.extend(("## Task", draft.brief.instruction.strip()))
    if draft.artifacts:
        deliverables = ["## Required deliverables"]
        for artifact in draft.artifacts:
            requirement = "required" if artifact.required else "optional"
            description = f" -- {artifact.description}" if artifact.description else ""
            deliverables.append(
                f"- `{artifact.path}` ({artifact.format}, {requirement}){description}"
            )
        sections.append("\n".join(deliverables))
    sections.extend(
        (
            "## Completion",
            "Place the requested outputs at the paths above. Evaluation checks the final "
            "scientific outputs, not the particular method used to produce them.",
        )
    )
    return "\n\n".join(sections).strip() + "\n"


def render_task_toml(draft: TaskDraft) -> str:
    metadata = draft.metadata
    artifacts = [f"/app/{item.path.replace('\\', '/')}" for item in draft.artifacts]
    lines = [
        "# Generated by harbor-marimo Task Studio. Review before benchmark submission.",
        'schema_version = "1.0"',
        f"artifacts = {_toml_array(artifacts)}",
        "",
        "[metadata]",
        f"author_name = {_toml_string(metadata.author_name)}",
        f"author_email = {_toml_string(metadata.author_email)}",
        f"author_organization = {_toml_string(metadata.author_organization)}",
        f"author_profile = {_toml_string(metadata.author_profile)}",
        f"research_advisor = {_toml_string(metadata.research_advisor)}",
        f"difficulty_explanation = {_toml_string(draft.brief.difficulty_explanation)}",
        f"solution_explanation = {_toml_string(draft.brief.solution_explanation)}",
        f"verification_explanation = {_toml_string(draft.brief.verification_explanation)}",
        f"domain = {_toml_string(metadata.domain)}",
        f"field = {_toml_string(metadata.field)}",
        f"subfield = {_toml_string(metadata.subfield)}",
        f"tags = {_toml_array(list(metadata.tags))}",
        f"expert_time_estimate_hours = {metadata.expert_time_estimate_hours}",
        f"relevant_experience = {_toml_string(metadata.relevant_experience)}",
        f"conflicts_of_interest = {_toml_string(metadata.conflicts_of_interest)}",
        "",
        "[verifier]",
        f"timeout_sec = {float(draft.verifier_timeout_sec)}",
        'environment_mode = "separate"',
        "",
        "[agent]",
        f"timeout_sec = {float(draft.agent_timeout_sec)}",
        "",
        "[environment]",
        f"build_timeout_sec = {float(draft.build_timeout_sec)}",
        f"cpus = {draft.cpus}",
        f"memory_mb = {draft.memory_mb}",
        f"storage_mb = {draft.storage_mb}",
        f"gpus = {draft.gpus}",
        f"allow_internet = {str(draft.allow_internet).lower()}",
    ]
    return "\n".join(lines) + "\n"


def _toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _toml_array(values: list[str]) -> str:
    return "[" + ", ".join(_toml_string(value) for value in values) + "]"
