#!/usr/bin/env python3
"""Generated by harbor-marimo. Review before benchmark submission."""

import csv
import json
import math
from pathlib import Path
import sys

CHECKS = [
    {
        "artifact": "results/posterior_summary.csv",
        "id": "posterior-columns",
        "parameters": {"columns": ["parameter", "mean", "r_hat", "ess"]},
        "type": "csv_columns",
    },
    {
        "artifact": "results/posterior_summary.csv",
        "id": "rhat-converged",
        "parameters": {"column": "r_hat", "value": 1.01},
        "type": "column_max",
    },
    {
        "artifact": "results/posterior_summary.csv",
        "id": "ess-adequate",
        "parameters": {"column": "ess", "value": 400},
        "type": "column_min",
    },
    {
        "artifact": "results/convergence.json",
        "id": "reported-convergence",
        "parameters": {"field": "status", "value": "converged"},
        "type": "json_equals",
    },
]


def run_check(root, check):
    path = (root / check["artifact"]).resolve()
    if not path.is_relative_to(root):
        return False, "artifact path escapes verifier root"
    kind = check["type"]
    params = check.get("parameters", {})
    if not path.is_file():
        return False, "artifact is missing"
    if kind == "csv_columns":
        with path.open("r", encoding="utf-8-sig", newline="") as handle:
            header = set(next(csv.reader(handle), []))
        missing = sorted(set(params.get("columns", [])) - header)
        return not missing, "missing columns: " + ", ".join(missing)
    if kind in {"column_min", "column_max"}:
        column = str(params["column"])
        threshold = float(params["value"])
        with path.open("r", encoding="utf-8-sig", newline="") as handle:
            values = [float(row[column]) for row in csv.DictReader(handle)]
        if not values or not all(math.isfinite(value) for value in values):
            return False, "column has no finite values"
        actual = min(values) if kind == "column_min" else max(values)
        passed = actual >= threshold if kind == "column_min" else actual <= threshold
        return passed, f"observed {actual:g} against {threshold:g}"
    if kind == "json_equals":
        value = json.loads(path.read_text(encoding="utf-8"))
        field = str(params["field"])
        return (
            isinstance(value, dict) and value.get(field) == params.get("value"),
            f"field {field}",
        )
    return False, f"unsupported check type: {kind}"


def main():
    root = Path(sys.argv[1] if len(sys.argv) > 1 else "/app/artifacts").resolve()
    results = []
    for check in CHECKS:
        try:
            passed, message = run_check(root, check)
        except Exception as exc:
            passed, message = False, f"{type(exc).__name__}: {exc}"
        results.append({"id": check["id"], "passed": passed, "message": message})
    print(
        json.dumps(
            {
                "checks": results,
                "passed": all(item["passed"] for item in results),
            },
            indent=2,
        )
    )
    return 0 if results and all(item["passed"] for item in results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
